import 'package:flutter/material.dart';

/// Static FAQ content, extracted from `faq_sheet.dart` so the widget file
/// carries only presentation. Edit copy here — no widget code required.

/// Item model for a FAQ entry. [onAction] is wired by the sheet (it needs a
/// live context), not stored in the static data.
class FaqItem {
  final String question;
  final String answer;
  final String category;
  final IconData icon;
  final String? actionLabel;

  const FaqItem({
    required this.question,
    required this.answer,
    required this.category,
    required this.icon,
    this.actionLabel,
  });
}

/// Category chips shown at the top of the FAQ sheet.
const List<String> faqCategories = [
  'All',
  'Documents',
  'Money',
  'AI & Voice',
  'Account & Tiers',
  'Support',
];

/// The full FAQ data set, grouped by category.
const List<FaqItem> faqItems = [
  // ── Documents ──────────────────────────────────────────────────────────
  FaqItem(
    category: 'Documents',
    icon: Icons.description_rounded,
    question: 'How does FV track document expiries?',
    answer:
        'FV monitors all your added documents (Emirates ID, Passports, Visas, Trade Licences, Mulkiya, Insurance) and notifies you at key lead times (90, 60, 30, 14, 7, and 1 day before expiration). You can also customize reminder lead times in Settings.',
  ),
  FaqItem(
    category: 'Documents',
    icon: Icons.autorenew_rounded,
    question: 'How do I mark a document as renewed?',
    answer:
        'Tap on any document card, then tap "Renew Document". You can set the new expiry date, attach a renewal fee receipt, and optionally auto-log the renewal cost into your Money expense tracker.',
  ),
  FaqItem(
    category: 'Documents',
    icon: Icons.folder_copy_rounded,
    question: 'What are Document Collections?',
    answer:
        'Collections organize your documents into distinct workspaces (e.g. Personal vs. Company). You can easily switch active collections from the top app header or from Profile settings.',
  ),
  FaqItem(
    category: 'Documents',
    icon: Icons.sd_storage_rounded,
    question: 'How are uploaded document files and attachments stored?',
    answer:
        "Uploaded document files (photos, scans, PDF receipts) are saved 100% locally on your device in the app's secure storage folder (/finavig/documents/). They remain strictly on your phone and are never uploaded to external cloud file servers.",
  ),
  FaqItem(
    category: 'Documents',
    icon: Icons.security_rounded,
    question: 'How are document details and metadata stored?',
    answer:
        'Document details (title, expiry date, authority, type, fees, and notes) are synchronized to your secure account cloud database (Supabase) for cross-device access, while also cached locally on your device for instant offline access.',
  ),

  // ── Money ──────────────────────────────────────────────────────────────
  FaqItem(
    category: 'Money',
    icon: Icons.payments_rounded,
    question: 'How does Smart Category matching work?',
    answer:
        'When logging an expense (e.g., "Paid 450 AED for DEWA"), FV automatically identifies UAE merchants and categories (like Utilities, Transport, Food, Govt Fees) using fuzzy matching and a UAE keyword dictionary.',
  ),
  FaqItem(
    category: 'Money',
    icon: Icons.repeat_rounded,
    question: 'How do Recurring Transactions and Cash Flow work?',
    answer:
        'Mark any expense or income as "Repeat Monthly/Yearly". FV auto-logs them when due and calculates a 90-Day Cash Flow forecast combining bank balance, upcoming recurring bills, and document renewal fees.',
  ),
  FaqItem(
    category: 'Money',
    icon: Icons.show_chart_rounded,
    question: 'What is a Bill Spike anomaly alert?',
    answer:
        'FV automatically detects sudden price increases in recurring expenses (e.g., a utility bill jumping 35%+ higher than your average) and alerts you so you can review potential overcharges.',
  ),

  // ── AI & Voice ─────────────────────────────────────────────────────────
  FaqItem(
    category: 'AI & Voice',
    icon: Icons.graphic_eq_rounded,
    question: 'How do I log records using Voice or Text?',
    answer:
        'Tap the Voice / Sparkle button on the Home or Money screen and speak or type naturally (e.g., "Spent 85 AED on Uber today"). FV extracts the amount, vendor, category, and date automatically.',
  ),
  FaqItem(
    category: 'AI & Voice',
    icon: Icons.auto_awesome_rounded,
    question: 'Do I need a Gemini API key for AI features?',
    answer:
        'No! FV includes built-in smart templates out of the box. Adding your free Gemini API key in Settings is optional and enables deeper executive summaries generated by Google Gemini.',
  ),

  // ── Account & Tiers ────────────────────────────────────────────────────
  FaqItem(
    category: 'Account & Tiers',
    icon: Icons.wifi_off_rounded,
    question: 'Does FV work offline without internet?',
    answer:
        'Yes! FV uses local-first caching. All your data is saved locally on your device for fast offline access and automatically syncs with cloud database when reconnected.',
  ),
  FaqItem(
    category: 'Account & Tiers',
    icon: Icons.workspace_premium_rounded,
    question: 'What are the differences between Free, Plus, and Business tiers?',
    answer:
        '• Free: 1 Personal collection & up to 10 active documents.\n• Plus: 1 Company collection & up to 100 documents.\n• Business: Unlimited Company collections, team features & unlimited AI summaries.',
  ),
  FaqItem(
    category: 'Account & Tiers',
    icon: Icons.lock_outline_rounded,
    question: 'What happens to my data if my plan changes?',
    answer:
        'Your data is completely safe and is never deleted. If your plan downgrades, surplus company collections are safely locked in read-only mode until you upgrade your plan.',
  ),

  // ── Support ────────────────────────────────────────────────────────────
  FaqItem(
    category: 'Support',
    icon: Icons.support_agent_rounded,
    question: 'How can I submit a support request or report a bug?',
    answer:
        'Tap "Submit a Request" in Profile → Help & Support, or tap the button below to send a message to our support team. You can track all your submissions in "My Requests".',
    actionLabel: 'Submit Support Ticket',
  ),
  FaqItem(
    category: 'Support',
    icon: Icons.contact_support_rounded,
    question: 'Where can I track the status of my support ticket?',
    answer:
        'Go to Profile → Help & Support → "My Requests". There you will see all your active and resolved tickets along with admin status updates.',
  ),
];
