# R8 rules for the release build.
# Generated by AGP (build/app/outputs/mapping/release/missing_rules.txt):
# google_mlkit_text_recognition ships a common artifact whose recognizer
# options reference the per-script (Chinese/Devanagari/Japanese/Korean)
# artifacts. Those are optional at runtime for Finavig (Latin-script OCR
# only), so simply silence the missing-class warnings.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
